esd:
  port:
    http:
      name: http
      host: 0.0.0.0
      port: 8080
      sock_type: 1
      open_http_protocol: true
  process:
    task-1:
      class_name: ESD\Plugins\ProcessRPC\ExampleClass\TestProcess
      group_name: TaskGroup
